#!/bin/bash

rsync -rvz --progress --delete --exclude-from=/home/jason/public_html/lando-wordpress/wp-content/themes/ucsc-pbsci/rsync-exclude.txt ~/public_html/lando-wordpress/wp-content/themes/ucsc-pbsci/ ~/public_html/ucsc-pbsci/wp-content/themes/ucsc-pbsci/