#!/bin/bash

rsync --update -rvz --progress --delete --exclude-from=/home/jason/public_html/lando-test/wp-content/themes/ucsc-pbsci/rsync-exclude.txt ~/public_html/lando-test/wp-content/uploads/ ~/public_html/ucsc-pbsci/wp-content/uploads/