#!/bin/bash

rsync -rvz --progress --delete --exclude-from=/home/jason/Projects/local-pbsci/wp-content/themes/ucsc-pbsci/rsync-exclude.txt ~/Projects/local-pbsci/wp-content/themes/ucsc-pbsci/ ~/Projects/ucsc-pbsci/wp-content/themes/ucsc-pbsci/